using System.Diagnostics;
using System.Globalization;
using System.Linq.Expressions;
using System.Text.Json;
using EvangelionERPV2.OpportunityRadarModule.Application.Configs;
using EvangelionERPV2.OpportunityRadarModule.Application.Interface;
using EvangelionERPV2.Shared.DTOs;
using EvangelionERPV2.Shared.Entities;
using EvangelionERPV2.Shared.Enums;
using EvangelionERPV2.Shared.Exceptions;
using EvangelionERPV2.Shared.Repositories;
using Microsoft.Extensions.Options;
using Prometheus;
using Serilog;
using Serilog.Context;

namespace EvangelionERPV2.OpportunityRadarModule.Application.Services
{
    public class OpportunityRadarService : IOpportunityRadarService
    {
        private const string StatusNew = "new";
        private const string StatusInAnalysis = "in_analysis";
        private const string StatusAccepted = "accepted";
        private const string StatusExecuted = "executed";
        private const string StatusArchived = "archived";

        private const string FeedbackAccepted = "accepted";
        private const string FeedbackRejected = "rejected";
        private const string FeedbackIgnored = "ignored";
        private const string FeedbackInAnalysis = "in_analysis";
        private const string FeedbackImplemented = "implemented";

        private const string TypeCrossSell = "cross_sell";
        private const string TypeBundle = "bundle_margin";
        private const string TypeSuppressedDemand = "suppressed_demand";
        private const string TypeLowStock = "low_stock";
        private const string TypeSupplierTco = "supplier_hidden_cost";
        private const string TypeCommercialReallocation = "commercial_reallocation";

        private static readonly HashSet<string> ManagedFeedbackStatuses =
        [
            FeedbackAccepted,
            FeedbackImplemented
        ];

        private static readonly HashSet<string> ValidFeedbackStatuses =
        [
            FeedbackAccepted,
            FeedbackRejected,
            FeedbackIgnored,
            FeedbackInAnalysis,
            FeedbackImplemented
        ];

        private static readonly HashSet<int> FinalizedOrderStatuses =
        [
            2,
            3,
            4,
            5
        ];

        private static readonly HashSet<int> OpenOrderStatuses =
        [
            0,
            1
        ];

        private static readonly Counter GeneratedCounter = Metrics.CreateCounter(
            "evangelion_opportunity_generated_total",
            "Total opportunities generated by the hidden opportunities radar",
            new CounterConfiguration { LabelNames = ["type"] });

        private static readonly Counter FeedbackCounter = Metrics.CreateCounter(
            "evangelion_opportunity_feedback_total",
            "Total feedback actions sent to radar recommendations",
            new CounterConfiguration { LabelNames = ["status"] });

        private static readonly Histogram RunDurationHistogram = Metrics.CreateHistogram(
            "evangelion_opportunity_run_duration_seconds",
            "Radar processing duration in seconds",
            new HistogramConfiguration { Buckets = Histogram.ExponentialBuckets(0.1, 2, 10) });

        private static readonly Gauge AcceptanceRateGauge = Metrics.CreateGauge(
            "evangelion_opportunity_acceptance_rate",
            "Current acceptance rate for opportunities",
            new GaugeConfiguration { LabelNames = ["enterprise_id"] });

        private static readonly Gauge ImplementationRateGauge = Metrics.CreateGauge(
            "evangelion_opportunity_implementation_rate",
            "Current implementation rate for opportunities",
            new GaugeConfiguration { LabelNames = ["enterprise_id"] });

        private static readonly Gauge UpliftRealVsEstimatedGauge = Metrics.CreateGauge(
            "evangelion_opportunity_uplift_real_vs_estimated",
            "Current ratio between real and estimated margin uplift",
            new GaugeConfiguration { LabelNames = ["enterprise_id"] });

        private static readonly Gauge ProcessingTimeGauge = Metrics.CreateGauge(
            "evangelion_opportunity_processing_time_ms",
            "Latest radar processing time in milliseconds",
            new GaugeConfiguration { LabelNames = ["enterprise_id"] });

        private readonly IRepository<Opportunity> _opportunityRepository;
        private readonly IRepository<OpportunitySignal> _signalRepository;
        private readonly IRepository<OpportunityRecommendation> _recommendationRepository;
        private readonly IRepository<OpportunityFeedback> _feedbackRepository;
        private readonly IRepository<OpportunityRunLog> _runLogRepository;
        private readonly IRepository<Order> _orderRepository;
        private readonly IRepository<OrderedProduct> _orderedProductRepository;
        private readonly IRepository<Product> _productRepository;
        private readonly IRepository<Customer> _customerRepository;
        private readonly IRepository<PayableBill> _payableBillRepository;
        private readonly IRepository<PayableBillProduct> _payableBillProductRepository;
        private readonly OpportunityRadarSettings _settings;

        public OpportunityRadarService(
            IRepository<Opportunity> opportunityRepository,
            IRepository<OpportunitySignal> signalRepository,
            IRepository<OpportunityRecommendation> recommendationRepository,
            IRepository<OpportunityFeedback> feedbackRepository,
            IRepository<OpportunityRunLog> runLogRepository,
            IRepository<Order> orderRepository,
            IRepository<OrderedProduct> orderedProductRepository,
            IRepository<Product> productRepository,
            IRepository<Customer> customerRepository,
            IRepository<PayableBill> payableBillRepository,
            IRepository<PayableBillProduct> payableBillProductRepository,
            IOptions<OpportunityRadarSettings> settings)
        {
            _opportunityRepository = opportunityRepository;
            _signalRepository = signalRepository;
            _recommendationRepository = recommendationRepository;
            _feedbackRepository = feedbackRepository;
            _runLogRepository = runLogRepository;
            _orderRepository = orderRepository;
            _orderedProductRepository = orderedProductRepository;
            _productRepository = productRepository;
            _customerRepository = customerRepository;
            _payableBillRepository = payableBillRepository;
            _payableBillProductRepository = payableBillProductRepository;
            _settings = settings.Value;
        }

        public async Task<PaginatedResultDTO<OpportunityDTO>> GetOpportunitiesAsync(Guid enterpriseId, OpportunityFilterDTO filter)
        {
            EnsureRadarEnabled();
            filter ??= new OpportunityFilterDTO();

            var opportunities = await SafeGetAllAsync(
                _opportunityRepository,
                BuildOpportunityPredicate(enterpriseId, filter));

            var filtered = ApplySort(opportunities, filter).ToList();
            var total = filtered.Count;
            var page = Math.Max(1, filter.Page);
            var pageSize = Math.Clamp(filter.PageSize <= 0 ? 25 : filter.PageSize, 1, 200);

            var paged = filtered
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();

            var dtoItems = await MapOpportunitiesAsync(paged);

            return new PaginatedResultDTO<OpportunityDTO>
            {
                Items = dtoItems,
                TotalItems = total,
                Page = page,
                PageSize = pageSize
            };
        }

        public async Task<OpportunityDTO?> GetOpportunityByIdAsync(Guid id, Guid enterpriseId)
        {
            EnsureRadarEnabled();

            var opportunity = await _opportunityRepository.GetByIdAsync(id);
            if (opportunity == null || opportunity.IsActive != true || opportunity.EnterpriseId != enterpriseId)
                return null;

            var mapped = await MapOpportunitiesAsync([opportunity]);
            return mapped.FirstOrDefault();
        }

        public async Task<OpportunityFeedbackDTO> AddFeedbackAsync(
            Guid enterpriseId,
            Guid opportunityId,
            Guid? userId,
            OpportunityFeedbackRequestDTO request,
            bool canApproveExecution)
        {
            EnsureRadarEnabled();
            request ??= new OpportunityFeedbackRequestDTO();

            var normalizedStatus = NormalizeStatus(request.Status);
            if (!ValidFeedbackStatuses.Contains(normalizedStatus))
                throw new InsertDatabaseException("Invalid feedback status. Use in_analysis, accepted, rejected, ignored or implemented.");

            if (ManagedFeedbackStatuses.Contains(normalizedStatus) && !canApproveExecution)
                throw new InsertDatabaseException("Only managers can accept or implement opportunities.");

            var opportunity = await _opportunityRepository.GetByIdAsync(opportunityId);
            if (opportunity == null || opportunity.IsActive != true || opportunity.EnterpriseId != enterpriseId)
                throw new NotFoundDatabaseException("Opportunity was not found for this enterprise.");

            var now = DateTime.UtcNow;
            var feedback = new OpportunityFeedback
            {
                Id = Guid.NewGuid(),
                OpportunityId = opportunityId,
                UserId = userId,
                Status = normalizedStatus,
                Comment = request.Comment?.Trim() ?? string.Empty,
                MetadataJson = string.IsNullOrWhiteSpace(request.MetadataJson) ? "{}" : request.MetadataJson,
                RealRevenueImpact = request.RealRevenueImpact,
                RealMarginImpact = request.RealMarginImpact,
                RealCashImpact = request.RealCashImpact,
                CreatedAt = now,
                UpdatedAt = now,
                IsActive = true
            };

            await _feedbackRepository.CreateAsync(feedback);

            opportunity.Status = normalizedStatus switch
            {
                FeedbackInAnalysis => StatusInAnalysis,
                FeedbackAccepted => StatusAccepted,
                FeedbackImplemented => StatusExecuted,
                FeedbackRejected => StatusArchived,
                _ => StatusArchived
            };

            opportunity.UpdatedAt = now;
            opportunity.LastEvaluatedAt = now;
            _opportunityRepository.Update(opportunity);
            await _opportunityRepository.CommitAsync();

            FeedbackCounter.WithLabels(normalizedStatus).Inc();
            await UpdateKpiGaugesAsync(enterpriseId);

            return new OpportunityFeedbackDTO
            {
                Id = feedback.Id,
                OpportunityId = feedback.OpportunityId,
                UserId = feedback.UserId,
                Status = feedback.Status,
                Comment = feedback.Comment,
                MetadataJson = feedback.MetadataJson,
                RealRevenueImpact = feedback.RealRevenueImpact,
                RealMarginImpact = feedback.RealMarginImpact,
                RealCashImpact = feedback.RealCashImpact,
                CreatedAt = feedback.CreatedAt
            };
        }

        public async Task<OpportunityRunLogDTO> RecomputeAsync(
            Guid enterpriseId,
            Guid? requestedByUserId,
            OpportunityRecomputeRequestDTO request,
            string triggerType)
        {
            EnsureRadarEnabled();
            request ??= new OpportunityRecomputeRequestDTO();

            var runId = Guid.NewGuid();
            var now = DateTime.UtcNow;
            var historyWindowDays = request.HistoryWindowDays > 0
                ? request.HistoryWindowDays
                : _settings.DefaultHistoryWindowDays;
            var minSampleOrders = Math.Max(2, _settings.MinimumSampleOrders);

            var runLog = new OpportunityRunLog
            {
                Id = Guid.NewGuid(),
                RunId = runId,
                EnterpriseId = enterpriseId,
                RequestedByUserId = requestedByUserId,
                TriggerType = string.IsNullOrWhiteSpace(triggerType) ? "manual" : triggerType.ToLowerInvariant(),
                Status = "running",
                StartedAt = now,
                CorrelationId = Activity.Current?.Id ?? Guid.NewGuid().ToString("N", CultureInfo.InvariantCulture),
                CreatedAt = now,
                UpdatedAt = now,
                IsActive = true
            };

            await _runLogRepository.CreateAsync(runLog);
            await _runLogRepository.CommitAsync();

            var stopwatch = Stopwatch.StartNew();

            using var _ = RunDurationHistogram.NewTimer();
            using (LogContext.PushProperty("run_id", runId))
            {
                try
                {
                    Log.Information("Radar recompute started for enterprise {EnterpriseId}", enterpriseId);
                    var windowStart = now.Date.AddDays(-historyWindowDays);
                    var context = await BuildRadarContextAsync(enterpriseId, windowStart, historyWindowDays);
                    var candidates = DetectOpportunities(context, minSampleOrders);
                    if (candidates.Count == 0 && minSampleOrders > 2)
                    {
                        candidates = DetectOpportunities(context, 2);
                    }

                    var prioritized = Prioritize(candidates);

                    var persistResult = await UpsertOpportunitiesAsync(
                        enterpriseId,
                        runId,
                        prioritized,
                        request.OnlyOpenOpportunities,
                        now);

                    stopwatch.Stop();

                    runLog.Status = "completed";
                    runLog.TotalGenerated = persistResult.Generated;
                    runLog.TotalUpdated = persistResult.Updated;
                    runLog.TotalArchived = persistResult.Archived;
                    runLog.DurationMs = (int)stopwatch.ElapsedMilliseconds;
                    runLog.DetectorStatsJson = JsonSerializer.Serialize(persistResult.GeneratedByType);
                    runLog.FinishedAt = DateTime.UtcNow;
                    runLog.UpdatedAt = DateTime.UtcNow;
                    _runLogRepository.Update(runLog);
                    await _runLogRepository.CommitAsync();

                    ProcessingTimeGauge.WithLabels(enterpriseId.ToString()).Set(runLog.DurationMs);

                    foreach (var item in persistResult.GeneratedByType)
                    {
                        GeneratedCounter.WithLabels(item.Key).Inc(item.Value);
                    }

                    await UpdateKpiGaugesAsync(enterpriseId);

                    Log.Information(
                        "Radar recompute finished for enterprise {EnterpriseId}. generated={Generated}, updated={Updated}, archived={Archived}, durationMs={DurationMs}",
                        enterpriseId,
                        persistResult.Generated,
                        persistResult.Updated,
                        persistResult.Archived,
                        runLog.DurationMs);

                    return MapRunLog(runLog);
                }
                catch (Exception ex)
                {
                    stopwatch.Stop();

                    runLog.Status = "failed";
                    runLog.ErrorMessage = ex.Message;
                    runLog.DurationMs = (int)stopwatch.ElapsedMilliseconds;
                    runLog.FinishedAt = DateTime.UtcNow;
                    runLog.UpdatedAt = DateTime.UtcNow;
                    _runLogRepository.Update(runLog);
                    await _runLogRepository.CommitAsync();

                    Log.Error(ex, "Radar recompute failed for enterprise {EnterpriseId}", enterpriseId);
                    throw;
                }
            }
        }

        public async Task<OpportunitySummaryDTO> GetSummaryAsync(Guid enterpriseId)
        {
            EnsureRadarEnabled();
            var opportunities = await SafeGetAllAsync(_opportunityRepository,
                x => x.IsActive == true && x.EnterpriseId == enterpriseId);

            var runLogs = await SafeGetAllAsync(_runLogRepository,
                x => x.IsActive == true && x.EnterpriseId == enterpriseId && x.Status == "completed");

            var feedbacks = await GetFeedbacksByOpportunityIdsAsync(opportunities.Select(o => o.Id));

            var total = opportunities.Count;
            var accepted = opportunities.Count(x => x.Status == StatusAccepted || x.Status == StatusExecuted);
            var executed = opportunities.Count(x => x.Status == StatusExecuted);

            var estimatedMarginOnExecuted = opportunities
                .Where(x => x.Status == StatusExecuted)
                .Sum(x => x.EstimatedMarginImpact);

            var realMarginOnImplemented = feedbacks
                .Where(x => x.Status == FeedbackImplemented)
                .Sum(x => x.RealMarginImpact ?? 0);

            var acceptanceRate = total <= 0 ? 0 : (double)accepted / total;
            var implementationRate = accepted <= 0 ? 0 : (double)executed / accepted;
            var uplift = estimatedMarginOnExecuted <= 0
                ? 0
                : realMarginOnImplemented / estimatedMarginOnExecuted;

            var lastRun = runLogs
                .OrderByDescending(x => x.StartedAt)
                .FirstOrDefault();

            var summary = new OpportunitySummaryDTO
            {
                Total = total,
                NewCount = opportunities.Count(x => x.Status == StatusNew),
                InAnalysisCount = opportunities.Count(x => x.Status == StatusInAnalysis),
                AcceptedCount = opportunities.Count(x => x.Status == StatusAccepted),
                ExecutedCount = opportunities.Count(x => x.Status == StatusExecuted),
                ArchivedCount = opportunities.Count(x => x.Status == StatusArchived),
                EstimatedRevenueImpact = opportunities.Sum(x => x.EstimatedRevenueImpact),
                EstimatedMarginImpact = opportunities.Sum(x => x.EstimatedMarginImpact),
                EstimatedCashImpact = opportunities.Sum(x => x.EstimatedCashImpact),
                AcceptanceRate = Math.Round(acceptanceRate, 4),
                ImplementationRate = Math.Round(implementationRate, 4),
                RealVsEstimatedUplift = Math.Round(uplift, 4),
                AverageProcessingTimeMs = runLogs.Count == 0 ? 0 : Math.Round(runLogs.Average(x => x.DurationMs), 2),
                LastRunId = lastRun?.RunId,
                LastRunAt = lastRun?.StartedAt,
                OpportunitiesByType = opportunities
                    .GroupBy(x => x.Type)
                    .ToDictionary(x => x.Key, x => x.Count())
            };

            AcceptanceRateGauge.WithLabels(enterpriseId.ToString()).Set(summary.AcceptanceRate);
            ImplementationRateGauge.WithLabels(enterpriseId.ToString()).Set(summary.ImplementationRate);
            UpliftRealVsEstimatedGauge.WithLabels(enterpriseId.ToString()).Set(summary.RealVsEstimatedUplift);

            return summary;
        }

        private static Expression<Func<Opportunity, bool>> BuildOpportunityPredicate(Guid enterpriseId, OpportunityFilterDTO filter)
        {
            var normalizedType = string.IsNullOrWhiteSpace(filter.Type)
                ? null
                : filter.Type.Trim().ToLowerInvariant();

            var normalizedStatus = string.IsNullOrWhiteSpace(filter.Status)
                ? null
                : filter.Status.Trim().ToLowerInvariant();

            var minScore = filter.MinScore;
            var maxScore = filter.MaxScore;
            var minImpact = filter.MinImpact;
            var maxImpact = filter.MaxImpact;
            var startDate = filter.StartDate;
            var endDate = filter.EndDate;

            return x => x.IsActive == true
                        && x.EnterpriseId == enterpriseId
                        && (normalizedType == null || x.Type.ToLower() == normalizedType)
                        && (normalizedStatus == null || x.Status.ToLower() == normalizedStatus)
                        && (!minScore.HasValue || x.ConfidenceScore >= minScore.Value)
                        && (!maxScore.HasValue || x.ConfidenceScore <= maxScore.Value)
                        && (!minImpact.HasValue || x.EstimatedMarginImpact >= minImpact.Value)
                        && (!maxImpact.HasValue || x.EstimatedMarginImpact <= maxImpact.Value)
                        && (!startDate.HasValue || x.DetectedAt >= startDate.Value)
                        && (!endDate.HasValue || x.DetectedAt <= endDate.Value);
        }

        private IEnumerable<Opportunity> ApplySort(IEnumerable<Opportunity> source, OpportunityFilterDTO filter)
        {
            var query = source;
            var sortBy = (filter.SortBy ?? "priority").Trim().ToLowerInvariant();
            var descending = filter.Descending;

            return sortBy switch
            {
                "score" => descending
                    ? query.OrderByDescending(x => x.ConfidenceScore).ThenByDescending(x => x.PriorityScore)
                    : query.OrderBy(x => x.ConfidenceScore).ThenBy(x => x.PriorityScore),
                "impact" => descending
                    ? query.OrderByDescending(x => x.EstimatedMarginImpact).ThenByDescending(x => x.PriorityScore)
                    : query.OrderBy(x => x.EstimatedMarginImpact).ThenBy(x => x.PriorityScore),
                "detected" => descending
                    ? query.OrderByDescending(x => x.DetectedAt)
                    : query.OrderBy(x => x.DetectedAt),
                "status" => descending
                    ? query.OrderByDescending(x => x.Status).ThenByDescending(x => x.PriorityScore)
                    : query.OrderBy(x => x.Status).ThenBy(x => x.PriorityScore),
                _ => descending
                    ? query.OrderByDescending(x => x.PriorityScore).ThenByDescending(x => x.ConfidenceScore)
                    : query.OrderBy(x => x.PriorityScore).ThenBy(x => x.ConfidenceScore)
            };
        }

        private async Task<List<OpportunityFeedback>> GetFeedbacksByOpportunityIdsAsync(IEnumerable<Guid> opportunityIds)
        {
            var result = new List<OpportunityFeedback>();
            var ids = opportunityIds.Distinct().ToList();
            if (ids.Count == 0)
                return result;

            foreach (var batch in ids.Chunk(1000))
            {
                var batchIds = batch.ToList();
                var feedbackBatch = await SafeGetAllAsync(
                    _feedbackRepository,
                    x => x.IsActive == true && batchIds.Contains(x.OpportunityId));

                if (feedbackBatch.Count > 0)
                    result.AddRange(feedbackBatch);
            }

            return result;
        }

        private async Task<List<OpportunityDTO>> MapOpportunitiesAsync(IReadOnlyCollection<Opportunity> opportunities)
        {
            if (opportunities.Count == 0)
                return [];

            var ids = opportunities.Select(x => x.Id).ToHashSet();

            var signals = await SafeGetAllAsync(_signalRepository,
                x => x.IsActive == true && ids.Contains(x.OpportunityId));

            var recommendations = await SafeGetAllAsync(_recommendationRepository,
                x => x.IsActive == true && ids.Contains(x.OpportunityId));

            var feedbacks = await SafeGetAllAsync(_feedbackRepository,
                x => x.IsActive == true && ids.Contains(x.OpportunityId));

            var signalsByOpportunity = signals
                .GroupBy(x => x.OpportunityId)
                .ToDictionary(x => x.Key, x => x.ToList());

            var recommendationByOpportunity = recommendations
                .GroupBy(x => x.OpportunityId)
                .ToDictionary(x => x.Key, x => x.OrderByDescending(r => r.CreatedAt).First());

            var feedbackByOpportunity = feedbacks
                .GroupBy(x => x.OpportunityId)
                .ToDictionary(x => x.Key, x => x.OrderByDescending(f => f.CreatedAt).ToList());

            return opportunities
                .Select(opportunity =>
                {
                    signalsByOpportunity.TryGetValue(opportunity.Id, out var opportunitySignals);
                    recommendationByOpportunity.TryGetValue(opportunity.Id, out var opportunityRecommendation);
                    feedbackByOpportunity.TryGetValue(opportunity.Id, out var opportunityFeedbacks);

                    return new OpportunityDTO
                    {
                        Id = opportunity.Id,
                        EnterpriseId = opportunity.EnterpriseId,
                        Type = opportunity.Type,
                        Status = opportunity.Status,
                        Title = opportunity.Title,
                        Description = opportunity.Description,
                        SourceRule = opportunity.SourceRule,
                        SourceModel = opportunity.SourceModel,
                        Hypothesis = opportunity.Hypothesis,
                        ExplainabilityJson = opportunity.ExplainabilityJson,
                        RunId = opportunity.RunId,
                        ConfidenceScore = Math.Round(opportunity.ConfidenceScore, 2),
                        EstimatedRevenueImpact = Math.Round(opportunity.EstimatedRevenueImpact, 2),
                        EstimatedMarginImpact = Math.Round(opportunity.EstimatedMarginImpact, 2),
                        EstimatedCashImpact = Math.Round(opportunity.EstimatedCashImpact, 2),
                        PriorityScore = Math.Round(opportunity.PriorityScore, 2),
                        DetectedAt = opportunity.DetectedAt,
                        LastEvaluatedAt = opportunity.LastEvaluatedAt,
                        Recommendation = opportunityRecommendation == null
                            ? null
                            : new OpportunityRecommendationDTO
                            {
                                Id = opportunityRecommendation.Id,
                                ActionTitle = opportunityRecommendation.ActionTitle,
                                ActionDescription = opportunityRecommendation.ActionDescription,
                                WhyRecommended = opportunityRecommendation.WhyRecommended,
                                ActionPayloadJson = opportunityRecommendation.ActionPayloadJson,
                                PriorityLabel = opportunityRecommendation.PriorityLabel
                            },
                        Signals = (opportunitySignals ?? [])
                            .OrderByDescending(x => x.SignalValue)
                            .Select(signal => new OpportunitySignalDTO
                            {
                                Id = signal.Id,
                                SignalType = signal.SignalType,
                                SignalKey = signal.SignalKey,
                                SignalValue = Math.Round(signal.SignalValue, 4),
                                Unit = signal.Unit,
                                MetadataJson = signal.MetadataJson,
                                SourceEntity = signal.SourceEntity,
                                SourceEntityId = signal.SourceEntityId,
                                CapturedAt = signal.CapturedAt
                            }).ToList(),
                        Feedbacks = (opportunityFeedbacks ?? [])
                            .Select(feedback => new OpportunityFeedbackDTO
                            {
                                Id = feedback.Id,
                                OpportunityId = feedback.OpportunityId,
                                UserId = feedback.UserId,
                                Status = feedback.Status,
                                Comment = feedback.Comment,
                                MetadataJson = feedback.MetadataJson,
                                RealRevenueImpact = feedback.RealRevenueImpact,
                                RealMarginImpact = feedback.RealMarginImpact,
                                RealCashImpact = feedback.RealCashImpact,
                                CreatedAt = feedback.CreatedAt
                            }).ToList()
                    };
                })
                .ToList();
        }

        private async Task<RadarDataContext> BuildRadarContextAsync(Guid enterpriseId, DateTime windowStart, int historyWindowDays)
        {
            var effectiveWindowStart = windowStart;
            var effectiveHistoryWindowDays = Math.Max(1, historyWindowDays);

            var orders = await SafeGetAllAsync(_orderRepository,
                x => x.IsActive == true
                     && x.EnterpriseId == enterpriseId
                     && x.CreatedAt >= windowStart);

            if (orders.Count == 0)
            {
                orders = await SafeGetAllAsync(_orderRepository,
                    x => x.IsActive == true
                         && x.EnterpriseId == enterpriseId);

                if (orders.Count > 0)
                {
                    effectiveWindowStart = orders.Min(x => x.CreatedAt).Date;
                    effectiveHistoryWindowDays = Math.Max(1, (DateTime.UtcNow.Date - effectiveWindowStart).Days + 1);
                }
            }

            var orderIds = orders.Select(x => x.Id).ToHashSet();

            var orderedProducts = orderIds.Count == 0
                ? []
                : await SafeGetAllAsync(_orderedProductRepository,
                    x => x.IsActive == true
                         && x.OrderId.HasValue
                         && orderIds.Contains(x.OrderId.Value));

            var productIds = orderedProducts.Select(x => x.ProductId).Distinct().ToHashSet();
            var products = productIds.Count == 0
                ? []
                : await SafeGetAllAsync(_productRepository,
                    x => x.IsActive == true
                         && x.EnterpriseId == enterpriseId
                         && productIds.Contains(x.Id));

            var customerIds = orders
                .Where(x => x.CustomerId.HasValue)
                .Select(x => x.CustomerId!.Value)
                .Distinct()
                .ToHashSet();

            var customers = customerIds.Count == 0
                ? []
                : await SafeGetAllAsync(_customerRepository,
                    x => x.IsActive == true
                         && x.EnterpriseId == enterpriseId
                         && customerIds.Contains(x.Id));

            var payableBills = await SafeGetAllAsync(_payableBillRepository,
                x => x.IsActive == true
                     && x.EnterpriseId == enterpriseId
                     && x.CreatedAt >= windowStart);

            if (payableBills.Count == 0)
            {
                payableBills = await SafeGetAllAsync(_payableBillRepository,
                    x => x.IsActive == true
                         && x.EnterpriseId == enterpriseId);
            }

            var payableBillIds = payableBills.Select(x => x.Id).ToHashSet();
            var payableItems = payableBillIds.Count == 0
                ? []
                : await SafeGetAllAsync(_payableBillProductRepository,
                    x => x.IsActive == true
                         && payableBillIds.Contains(x.PayableBillId));

            return new RadarDataContext
            {
                Orders = orders,
                OrderedProducts = orderedProducts,
                ProductsById = products.ToDictionary(x => x.Id, x => x),
                CustomersById = customers.ToDictionary(x => x.Id, x => x),
                PayableBills = payableBills,
                PayableItems = payableItems,
                WindowStart = effectiveWindowStart,
                HistoryWindowDays = effectiveHistoryWindowDays
            };
        }

        private List<OpportunityCandidate> DetectOpportunities(RadarDataContext context, int minSampleOrders)
        {
            var candidates = new List<OpportunityCandidate>();

            candidates.AddRange(DetectCrossSell(context, minSampleOrders));
            candidates.AddRange(DetectMarginBundles(context, minSampleOrders));
            candidates.AddRange(DetectSuppressedDemand(context));
            candidates.AddRange(DetectLowStock(context, minSampleOrders));
            candidates.AddRange(DetectSupplierHiddenCost(context, minSampleOrders));
            candidates.AddRange(DetectCommercialReallocation(context, minSampleOrders));

            return candidates;
        }

        private List<OpportunityCandidate> DetectCrossSell(RadarDataContext context, int minSampleOrders)
        {
            var orderProducts = BuildOrderProductSets(context);
            if (orderProducts.Count == 0)
                return [];

            var customerSegments = BuildCustomerSegments(context);
            var opportunities = new List<OpportunityCandidate>();
            var segmentValues = customerSegments.Values.Distinct().ToList();
            var demandOrderIds = ResolveDemandOrderScope(context.Orders);

            if (demandOrderIds.Count == 0)
                return [];

            if (segmentValues.Count == 0)
                segmentValues = ["all_customers"];

            foreach (var segmentValue in segmentValues)
            {
                var segmentOrderIds = segmentValue == "all_customers"
                    ? context.Orders
                        .Where(order => demandOrderIds.Contains(order.Id))
                        .Select(order => order.Id)
                        .ToList()
                    : context.Orders
                        .Where(order => order.CustomerId.HasValue
                                        && customerSegments.TryGetValue(order.CustomerId.Value, out var customerSegment)
                                        && customerSegment == segmentValue
                                        && demandOrderIds.Contains(order.Id))
                        .Select(order => order.Id)
                        .ToList();

                if (segmentOrderIds.Count < minSampleOrders)
                    continue;

                var pairs = BuildPairMetrics(orderProducts, segmentOrderIds);
                var trios = BuildTrioCounts(orderProducts, segmentOrderIds);

                var topPairs = pairs
                    .Where(pair => pair.SupportCount >= minSampleOrders && pair.Confidence >= 0.35)
                    .OrderByDescending(pair => pair.Confidence * pair.Support)
                    .Take(4)
                    .ToList();

                foreach (var pair in topPairs)
                {
                    if (!context.ProductsById.TryGetValue(pair.ProductA, out var productA)
                        || !context.ProductsById.TryGetValue(pair.ProductB, out var productB))
                    {
                        continue;
                    }

                    var trioBonus = trios.Any(trio => trio.Key.Contains(pair.ProductA) && trio.Key.Contains(pair.ProductB))
                        ? 7
                        : 0;

                    var targetPrice = Math.Max(productB.DefaultValue, 0);
                    var estimatedRevenue = Math.Max(0, segmentOrderIds.Count * (pair.Confidence - 0.2) * 0.2 * targetPrice);
                    var estimatedMargin = estimatedRevenue * 0.22;
                    var estimatedCash = estimatedMargin * 0.5;
                    var confidence = Clamp(45 + (pair.Confidence * 35) + (pair.Support * 20) + trioBonus, 0, 100);

                    var fingerprint = $"crosssell:{segmentValue}:{pair.ProductA:N}:{pair.ProductB:N}";

                    opportunities.Add(new OpportunityCandidate
                    {
                        Fingerprint = fingerprint,
                        Type = TypeCrossSell,
                        Title = $"Cross-sell signal for segment {segmentValue}",
                        Description = $"Customers buying {productA.Name} tend to also buy {productB.Name}.",
                        SourceRule = "cross_sell_segment_pair_confidence",
                        SourceModel = "rules-v1",
                        Hypothesis = "Pairs with strong co-purchase in a segment can improve ticket with targeted suggestions.",
                        ExplainabilityJson = JsonSerializer.Serialize(new
                        {
                            segment = segmentValue,
                            productA = productA.Name,
                            productB = productB.Name,
                            supportCount = pair.SupportCount,
                            support = pair.Support,
                            confidence = pair.Confidence
                        }),
                        ConfidenceScore = confidence,
                        EstimatedRevenueImpact = estimatedRevenue,
                        EstimatedMarginImpact = estimatedMargin,
                        EstimatedCashImpact = estimatedCash,
                        RecommendationActionTitle = "Enable segmented cross-sell",
                        RecommendationActionDescription = $"For segment {segmentValue}, add {productB.Name} as suggested item whenever {productA.Name} is in cart.",
                        WhyRecommended = "High co-purchase confidence and recurring support in recent orders.",
                        RecommendationPayloadJson = JsonSerializer.Serialize(new
                        {
                            segment = segmentValue,
                            baseProductId = pair.ProductA,
                            targetProductId = pair.ProductB,
                            confidence = Math.Round(pair.Confidence, 4),
                            support = Math.Round(pair.Support, 4)
                        }),
                        Signals =
                        [
                            new OpportunityCandidateSignal("pair_confidence", $"{pair.ProductA:N}-{pair.ProductB:N}", pair.Confidence, "ratio", "Order", pair.ProductA.ToString()),
                            new OpportunityCandidateSignal("pair_support", $"{pair.ProductA:N}-{pair.ProductB:N}", pair.Support, "ratio", "Order", pair.ProductB.ToString()),
                            new OpportunityCandidateSignal("segment_orders", segmentValue, segmentOrderIds.Count, "orders", "Customer", segmentValue)
                        ]
                    });
                }
            }

            return opportunities;
        }

        private List<OpportunityCandidate> DetectMarginBundles(RadarDataContext context, int minSampleOrders)
        {
            var orderProducts = BuildOrderProductSets(context);
            if (orderProducts.Count == 0)
                return [];

            var averageCostByProduct = BuildAverageCostByProduct(context);
            var dailyConsumption = BuildDailyConsumptionByProduct(context);
            var pairMetrics = BuildPairMetrics(orderProducts, orderProducts.Keys);

            var opportunities = new List<OpportunityCandidate>();

            foreach (var pair in pairMetrics.Where(x => x.SupportCount >= minSampleOrders))
            {
                if (!context.ProductsById.TryGetValue(pair.ProductA, out var productA)
                    || !context.ProductsById.TryGetValue(pair.ProductB, out var productB))
                {
                    continue;
                }

                var productACost = averageCostByProduct.TryGetValue(productA.Id, out var aCost) ? aCost : productA.DefaultValue * 0.78;
                var productBCost = averageCostByProduct.TryGetValue(productB.Id, out var bCost) ? bCost : productB.DefaultValue * 0.78;

                var priceA = Math.Max(0, productA.DefaultValue);
                var priceB = Math.Max(0, productB.DefaultValue);
                var grossPrice = priceA + priceB;

                if (grossPrice <= 0)
                    continue;

                var costTotal = Math.Max(0, productACost + productBCost);
                var bundleMargin = (grossPrice - costTotal) / grossPrice;

                var marginA = priceA <= 0 ? 0 : (priceA - productACost) / priceA;
                var marginB = priceB <= 0 ? 0 : (priceB - productBCost) / priceB;
                var baselineMargin = (marginA + marginB) / 2;
                var marginLift = bundleMargin - baselineMargin;

                if (marginLift <= 0.02)
                    continue;

                var coverageA = ResolveCoverageDays(productA, dailyConsumption);
                var coverageB = ResolveCoverageDays(productB, dailyConsumption);

                if (coverageA < 5 || coverageB < 5)
                    continue;

                var expectedOrders = Math.Max(1, pair.SupportCount * 0.4);
                var bundlePrice = grossPrice * 0.95;
                var estimatedRevenue = expectedOrders * bundlePrice;
                var estimatedMargin = estimatedRevenue * Math.Max(bundleMargin, 0.05);
                var estimatedCash = estimatedMargin * 0.45;

                var confidence = Clamp(40 + (pair.Support * 25) + (pair.Confidence * 25) + (marginLift * 100), 0, 100);
                var fingerprint = $"bundle:{pair.ProductA:N}:{pair.ProductB:N}";

                opportunities.Add(new OpportunityCandidate
                {
                    Fingerprint = fingerprint,
                    Type = TypeBundle,
                    Title = $"Bundle opportunity: {productA.Name} + {productB.Name}",
                    Description = "Suggested kit has stronger consolidated margin and healthy stock coverage.",
                    SourceRule = "bundle_margin_pair_rule",
                    SourceModel = "rules-v1",
                    Hypothesis = "Products bought together with positive margin lift should be sold as bundles.",
                    ExplainabilityJson = JsonSerializer.Serialize(new
                    {
                        productA = productA.Name,
                        productB = productB.Name,
                        bundleMargin = Math.Round(bundleMargin, 4),
                        marginLift = Math.Round(marginLift, 4),
                        coverageA = Math.Round(coverageA, 2),
                        coverageB = Math.Round(coverageB, 2)
                    }),
                    ConfidenceScore = confidence,
                    EstimatedRevenueImpact = estimatedRevenue,
                    EstimatedMarginImpact = estimatedMargin,
                    EstimatedCashImpact = estimatedCash,
                    RecommendationActionTitle = "Create margin-first bundle",
                    RecommendationActionDescription = $"Launch bundle {productA.Name} + {productB.Name} with controlled discount and dedicated campaign.",
                    WhyRecommended = "Bundle margin is above baseline and current coverage does not increase stockout risk.",
                    RecommendationPayloadJson = JsonSerializer.Serialize(new
                    {
                        productIds = new[] { pair.ProductA, pair.ProductB },
                        bundlePrice = Math.Round(bundlePrice, 2),
                        expectedOrders = Math.Round(expectedOrders, 2)
                    }),
                    Signals =
                    [
                        new OpportunityCandidateSignal("bundle_margin", fingerprint, bundleMargin, "ratio", "Product", pair.ProductA.ToString()),
                        new OpportunityCandidateSignal("bundle_margin_lift", fingerprint, marginLift, "ratio", "Product", pair.ProductB.ToString()),
                        new OpportunityCandidateSignal("bundle_support_count", fingerprint, pair.SupportCount, "orders", "Order", pair.ProductA.ToString())
                    ]
                });
            }

            return opportunities
                .OrderByDescending(x => x.EstimatedMarginImpact)
                .Take(5)
                .ToList();
        }

        private List<OpportunityCandidate> DetectSuppressedDemand(RadarDataContext context)
        {
            if (context.OrderedProducts.Count == 0)
                return [];

            var orderById = context.Orders.ToDictionary(x => x.Id, x => x);
            var demandOrderIds = ResolveDemandOrderScope(context.Orders);
            if (demandOrderIds.Count == 0)
                return [];

            var finalizedLines = context.OrderedProducts
                .Where(x => x.OrderId.HasValue
                            && orderById.ContainsKey(x.OrderId.Value)
                            && demandOrderIds.Contains(x.OrderId.Value))
                .ToList();

            if (finalizedLines.Count == 0)
                return [];

            var dailyConsumption = finalizedLines
                .GroupBy(x => x.ProductId)
                .ToDictionary(
                    x => x.Key,
                    x => x.Sum(line => line.Quantity) / Math.Max(1, context.HistoryWindowDays));

            var openDemand = context.OrderedProducts
                .Where(x => x.OrderId.HasValue
                            && orderById.TryGetValue(x.OrderId.Value, out var order)
                            && OpenOrderStatuses.Contains(order.Status))
                .GroupBy(x => x.ProductId)
                .ToDictionary(x => x.Key, x => x.Sum(line => line.Quantity));

            var opportunities = new List<OpportunityCandidate>();

            foreach (var item in dailyConsumption)
            {
                if (!context.ProductsById.TryGetValue(item.Key, out var product))
                    continue;

                var demandPerDay = item.Value;
                if (demandPerDay <= 0)
                    continue;

                var stock = Math.Max(0, product.StorageQuantity);
                var coverageDays = stock / demandPerDay;
                var pendingUnits = openDemand.TryGetValue(product.Id, out var open) ? open : 0;
                var stockoutGap = Math.Max(0, 7 - coverageDays);
                var lostUnits = pendingUnits + (stockoutGap * demandPerDay);

                if (lostUnits <= 1)
                    continue;

                var unitPrice = Math.Max(product.DefaultValue, 0);
                var estimatedRevenue = lostUnits * unitPrice;
                var estimatedMargin = estimatedRevenue * 0.2;
                var estimatedCash = estimatedMargin * 0.65;
                var confidence = Clamp(38 + Math.Min(35, pendingUnits * 2) + (coverageDays <= 1 ? 22 : 12), 0, 100);

                var fingerprint = $"suppressed-demand:{product.Id:N}";

                opportunities.Add(new OpportunityCandidate
                {
                    Fingerprint = fingerprint,
                    Type = TypeSuppressedDemand,
                    Title = $"Suppressed demand risk: {product.Name}",
                    Description = "Demand may be constrained by low stock and open order pressure.",
                    SourceRule = "suppressed_demand_open_orders_stock_gap",
                    SourceModel = "rules-v1",
                    Hypothesis = "Open order pressure and short coverage are a proxy for lost sales due to stockout.",
                    ExplainabilityJson = JsonSerializer.Serialize(new
                    {
                        product = product.Name,
                        pendingUnits,
                        dailyConsumption = Math.Round(demandPerDay, 4),
                        stock = Math.Round(stock, 2),
                        coverageDays = Math.Round(coverageDays, 2),
                        estimatedLostUnits = Math.Round(lostUnits, 2)
                    }),
                    ConfidenceScore = confidence,
                    EstimatedRevenueImpact = estimatedRevenue,
                    EstimatedMarginImpact = estimatedMargin,
                    EstimatedCashImpact = estimatedCash,
                    RecommendationActionTitle = "Replenish and protect availability",
                    RecommendationActionDescription = $"Prioritize replenishment of {product.Name} and reserve stock for open demand.",
                    WhyRecommended = "Coverage is short and demand pressure indicates potential lost revenue.",
                    RecommendationPayloadJson = JsonSerializer.Serialize(new
                    {
                        productId = product.Id,
                        recommendedReplenishment = Math.Round(Math.Max(lostUnits, demandPerDay * 10), 2)
                    }),
                    Signals =
                    [
                        new OpportunityCandidateSignal("coverage_days", product.Id.ToString(), coverageDays, "days", "Product", product.Id.ToString()),
                        new OpportunityCandidateSignal("open_demand_units", product.Id.ToString(), pendingUnits, "units", "Order", product.Id.ToString()),
                        new OpportunityCandidateSignal("lost_units_estimate", product.Id.ToString(), lostUnits, "units", "Order", product.Id.ToString())
                    ]
                });
            }

            return opportunities
                .OrderByDescending(x => x.EstimatedRevenueImpact)
                .Take(8)
                .ToList();
        }

        private List<OpportunityCandidate> DetectLowStock(RadarDataContext context, int minSampleOrders)
        {
            if (context.OrderedProducts.Count == 0 || context.ProductsById.Count == 0)
                return [];

            var orderById = context.Orders.ToDictionary(x => x.Id, x => x);
            var demandOrderIds = ResolveDemandOrderScope(context.Orders);
            if (demandOrderIds.Count < minSampleOrders)
                return [];

            var demandLines = context.OrderedProducts
                .Where(line => line.OrderId.HasValue
                               && orderById.ContainsKey(line.OrderId.Value)
                               && demandOrderIds.Contains(line.OrderId.Value))
                .ToList();

            if (demandLines.Count == 0)
                return [];

            var opportunities = new List<OpportunityCandidate>();
            foreach (var productGroup in demandLines.GroupBy(line => line.ProductId))
            {
                if (!context.ProductsById.TryGetValue(productGroup.Key, out var product))
                    continue;

                var totalSold = productGroup.Sum(line => Math.Max(0, line.Quantity));
                if (totalSold <= 0)
                    continue;

                var salesDates = productGroup
                    .Where(line => line.OrderId.HasValue && orderById.ContainsKey(line.OrderId.Value))
                    .Select(line => orderById[line.OrderId!.Value].CreatedAt.Date)
                    .Distinct()
                    .OrderBy(date => date)
                    .ToList();

                if (salesDates.Count < minSampleOrders)
                    continue;

                var averageDailySales = totalSold / Math.Max(1, context.HistoryWindowDays);
                if (averageDailySales <= 0)
                    continue;

                var intervalDays = new List<double>();
                for (var i = 1; i < salesDates.Count; i++)
                {
                    var interval = (salesDates[i] - salesDates[i - 1]).TotalDays;
                    if (interval > 0)
                        intervalDays.Add(interval);
                }

                var averageIntervalDays = intervalDays.Count == 0 ? 7 : intervalDays.Average();
                var lowStockThresholdDays = Math.Clamp((int)Math.Round(averageIntervalDays * 0.75), 3, 30);

                var currentStock = Math.Max(0, product.StorageQuantity);
                var coverageDays = currentStock / averageDailySales;

                if (coverageDays >= lowStockThresholdDays)
                    continue;

                var coverageGapDays = lowStockThresholdDays - coverageDays;
                var unitsAtRisk = Math.Max(0, coverageGapDays * averageDailySales);
                var suggestedReplenishment = Math.Max(0, (averageDailySales * (lowStockThresholdDays + 2)) - currentStock);
                var unitPrice = Math.Max(0, product.DefaultValue);

                var estimatedRevenue = unitsAtRisk * unitPrice;
                var estimatedMargin = estimatedRevenue * 0.2;
                var estimatedCash = estimatedMargin * 0.5;

                var sampleFactor = Math.Min(1d, salesDates.Count / (double)(minSampleOrders + 2));
                var confidence = Clamp(45 + (sampleFactor * 20) + Math.Min(25, coverageGapDays * 5), 0, 100);
                var fingerprint = $"low-stock:{product.Id:N}";

                opportunities.Add(new OpportunityCandidate
                {
                    Fingerprint = fingerprint,
                    Type = TypeLowStock,
                    Title = $"Low stock risk: {product.Name}",
                    Description = "Stock coverage is below expected threshold based on average sales cadence.",
                    SourceRule = "low_stock_average_sales_coverage",
                    SourceModel = "rules-v1",
                    Hypothesis = "When coverage by average daily sales drops below the inferred threshold, replenishment should be prioritized.",
                    ExplainabilityJson = JsonSerializer.Serialize(new
                    {
                        product = product.Name,
                        averageDailySales = Math.Round(averageDailySales, 4),
                        currentStock = Math.Round(currentStock, 2),
                        coverageDays = Math.Round(coverageDays, 2),
                        lowStockThresholdDays,
                        salesSamples = salesDates.Count
                    }),
                    ConfidenceScore = confidence,
                    EstimatedRevenueImpact = estimatedRevenue,
                    EstimatedMarginImpact = estimatedMargin,
                    EstimatedCashImpact = estimatedCash,
                    RecommendationActionTitle = "Replenish low-stock SKU",
                    RecommendationActionDescription = $"Replenish {product.Name} to recover at least {lowStockThresholdDays} days of coverage.",
                    WhyRecommended = "Coverage is below threshold inferred from the product's average sales pace.",
                    RecommendationPayloadJson = JsonSerializer.Serialize(new
                    {
                        productId = product.Id,
                        suggestedQuantity = Math.Round(suggestedReplenishment, 2),
                        thresholdDays = lowStockThresholdDays,
                        coverageDays = Math.Round(coverageDays, 2)
                    }),
                    Signals =
                    [
                        new OpportunityCandidateSignal("avg_daily_sales", product.Id.ToString(), averageDailySales, "units_per_day", "Order", product.Id.ToString()),
                        new OpportunityCandidateSignal("stock_coverage_days", product.Id.ToString(), coverageDays, "days", "Product", product.Id.ToString()),
                        new OpportunityCandidateSignal("low_stock_threshold_days", product.Id.ToString(), lowStockThresholdDays, "days", "Order", product.Id.ToString())
                    ]
                });
            }

            return opportunities
                .OrderByDescending(x => x.EstimatedMarginImpact)
                .Take(10)
                .ToList();
        }

        private List<OpportunityCandidate> DetectSupplierHiddenCost(RadarDataContext context, int minSampleOrders)
        {
            if (context.PayableBills.Count == 0 || context.PayableItems.Count == 0)
                return [];

            var billById = context.PayableBills.ToDictionary(x => x.Id, x => x);
            var grouped = context.PayableItems
                .Where(item => billById.ContainsKey(item.PayableBillId))
                .GroupBy(item => InferSupplierKey(billById[item.PayableBillId].Description))
                .Select(group =>
                {
                    var bills = group
                        .Select(item => billById[item.PayableBillId])
                        .DistinctBy(bill => bill.Id)
                        .ToList();

                    var quantity = group.Sum(item => item.Quantity);
                    var lineAmount = group.Sum(item => item.LineAmount);
                    var baseUnitCost = quantity <= 0 ? 0 : lineAmount / quantity;

                    var delayDays = bills
                        .Where(bill => bill.ProductsReceivedAt.HasValue)
                        .Select(bill => Math.Max(0, (bill.ProductsReceivedAt!.Value.Date - bill.DueDate.Date).TotalDays))
                        .ToList();

                    var avgDelay = delayDays.Count == 0 ? 0 : delayDays.Average();

                    var extraFreight = bills.Sum(bill =>
                    {
                        var billLines = group.Where(item => item.PayableBillId == bill.Id).Sum(item => item.LineAmount);
                        return Math.Max(0, bill.Amount - billLines);
                    });

                    var reworkRate = ComputeReworkRate(bills, group.ToList());
                    var delayPenalty = baseUnitCost * (avgDelay * 0.01);
                    var reworkPenalty = baseUnitCost * (reworkRate * 0.06);
                    var extraFreightPerUnit = quantity <= 0 ? 0 : extraFreight / quantity;
                    var tco = baseUnitCost + delayPenalty + reworkPenalty + extraFreightPerUnit;

                    return new SupplierCostSnapshot
                    {
                        SupplierKey = group.Key,
                        BillCount = bills.Count,
                        Quantity = quantity,
                        BaseUnitCost = baseUnitCost,
                        AverageDelayDays = avgDelay,
                        ReworkRate = reworkRate,
                        ExtraFreightPerUnit = extraFreightPerUnit,
                        TcoPerUnit = tco
                    };
                })
                .Where(snapshot => snapshot.BillCount >= minSampleOrders && snapshot.Quantity > 0)
                .ToList();

            if (grouped.Count < 2)
                return [];

            var best = grouped.OrderBy(x => x.TcoPerUnit).First();
            var opportunities = new List<OpportunityCandidate>();

            foreach (var supplier in grouped.Where(x => x.SupplierKey != best.SupplierKey))
            {
                var delta = supplier.TcoPerUnit - best.TcoPerUnit;
                if (delta <= 0.01)
                    continue;

                var potentialSavings = delta * supplier.Quantity;
                var confidence = Clamp(35 + (supplier.BillCount * 6) + Math.Min(30, delta * 120), 0, 100);
                var fingerprint = $"supplier-tco:{supplier.SupplierKey}:{best.SupplierKey}";

                opportunities.Add(new OpportunityCandidate
                {
                    Fingerprint = fingerprint,
                    Type = TypeSupplierTco,
                    Title = $"Supplier TCO optimization: {supplier.SupplierKey}",
                    Description = $"Supplier {supplier.SupplierKey} has higher total cost than {best.SupplierKey}.",
                    SourceRule = "supplier_tco_comparison_rule",
                    SourceModel = "rules-v1",
                    Hypothesis = "Suppliers should be ranked by total ownership cost, not only unit price.",
                    ExplainabilityJson = JsonSerializer.Serialize(new
                    {
                        supplier = supplier.SupplierKey,
                        alternative = best.SupplierKey,
                        supplierTco = Math.Round(supplier.TcoPerUnit, 4),
                        bestTco = Math.Round(best.TcoPerUnit, 4),
                        averageDelayDays = Math.Round(supplier.AverageDelayDays, 2),
                        reworkRate = Math.Round(supplier.ReworkRate, 4)
                    }),
                    ConfidenceScore = confidence,
                    EstimatedRevenueImpact = potentialSavings * 1.2,
                    EstimatedMarginImpact = potentialSavings,
                    EstimatedCashImpact = potentialSavings,
                    RecommendationActionTitle = "Prioritize lower-TCO supplier",
                    RecommendationActionDescription = $"Rebalance purchasing volume from {supplier.SupplierKey} to {best.SupplierKey} with controlled transition.",
                    WhyRecommended = "Measured TCO includes delay penalties, rework proxy and extra freight impacts.",
                    RecommendationPayloadJson = JsonSerializer.Serialize(new
                    {
                        supplier = supplier.SupplierKey,
                        suggestedAlternative = best.SupplierKey,
                        estimatedSavings = Math.Round(potentialSavings, 2)
                    }),
                    Signals =
                    [
                        new OpportunityCandidateSignal("supplier_tco", supplier.SupplierKey, supplier.TcoPerUnit, "currency_per_unit", "PayableBill", supplier.SupplierKey),
                        new OpportunityCandidateSignal("best_supplier_tco", best.SupplierKey, best.TcoPerUnit, "currency_per_unit", "PayableBill", best.SupplierKey),
                        new OpportunityCandidateSignal("supplier_avg_delay_days", supplier.SupplierKey, supplier.AverageDelayDays, "days", "PayableBill", supplier.SupplierKey)
                    ]
                });
            }

            return opportunities;
        }

        private List<OpportunityCandidate> DetectCommercialReallocation(RadarDataContext context, int minSampleOrders)
        {
            if (context.Orders.Count < minSampleOrders * 2)
                return [];

            var demandOrderIds = ResolveDemandOrderScope(context.Orders);
            if (demandOrderIds.Count < minSampleOrders)
                return [];

            var averageCostByProduct = BuildAverageCostByProduct(context);

            var groups = context.Orders
                .GroupBy(order =>
                {
                    if (!order.CustomerId.HasValue || !context.CustomersById.TryGetValue(order.CustomerId.Value, out var customer))
                        return "unknown|unknown";

                    return $"{InferSalesChannel(customer)}|{InferRegion(customer.Adress)}";
                })
                .Select(group =>
                {
                    var orders = group.ToList();
                    var finalizedOrders = orders
                        .Where(order => demandOrderIds.Contains(order.Id))
                        .ToList();

                    var orderIds = finalizedOrders.Select(order => order.Id).ToHashSet();
                    var lines = context.OrderedProducts
                        .Where(line => line.OrderId.HasValue && orderIds.Contains(line.OrderId.Value))
                        .ToList();

                    var revenue = finalizedOrders.Sum(order => Math.Max(0, order.TotalValue));
                    var cost = lines.Sum(line =>
                    {
                        var unitCost = averageCostByProduct.TryGetValue(line.ProductId, out var value)
                            ? value
                            : context.ProductsById.TryGetValue(line.ProductId, out var product)
                                ? product.DefaultValue * 0.78
                                : 0;
                        return Math.Max(0, line.Quantity * unitCost);
                    });

                    var margin = Math.Max(0, revenue - cost);
                    var finalizedCount = finalizedOrders.Count;
                    var conversionRate = orders.Count == 0 ? 0 : (double)finalizedCount / orders.Count;
                    var marginPerOrder = finalizedCount == 0 ? 0 : margin / finalizedCount;
                    var revenuePerOrder = finalizedCount == 0 ? 0 : revenue / finalizedCount;

                    return new CommercialGroupSnapshot
                    {
                        GroupKey = group.Key,
                        Orders = orders.Count,
                        FinalizedOrders = finalizedCount,
                        Revenue = revenue,
                        Margin = margin,
                        ConversionRate = conversionRate,
                        MarginPerOrder = marginPerOrder,
                        RevenuePerOrder = revenuePerOrder
                    };
                })
                .Where(snapshot => snapshot.FinalizedOrders >= minSampleOrders)
                .ToList();

            if (groups.Count < 2)
                return [];

            var best = groups
                .OrderByDescending(x => x.MarginPerOrder)
                .ThenByDescending(x => x.ConversionRate)
                .First();

            var worst = groups
                .OrderBy(x => x.MarginPerOrder)
                .ThenBy(x => x.ConversionRate)
                .First();

            if (best.GroupKey == worst.GroupKey)
                return [];

            var marginGap = best.MarginPerOrder - worst.MarginPerOrder;
            if (marginGap <= 1)
                return [];

            var shiftOrders = Math.Max(1, (int)Math.Floor(worst.Orders * 0.15));
            var estimatedMargin = shiftOrders * marginGap;
            var estimatedRevenue = shiftOrders * Math.Max(0, best.RevenuePerOrder - worst.RevenuePerOrder);
            var estimatedCash = estimatedMargin * 0.7;
            var confidence = Clamp(35 + Math.Min(35, marginGap * 3) + Math.Min(30, best.ConversionRate * 40), 0, 100);

            var fingerprint = $"reallocation:{worst.GroupKey}:{best.GroupKey}";
            var hypothesis = "Reallocating sales effort to groups with better margin-per-order can increase profitability.";

            return
            [
                new OpportunityCandidate
                {
                    Fingerprint = fingerprint,
                    Type = TypeCommercialReallocation,
                    Title = "Commercial effort reallocation",
                    Description = $"Move part of effort from {worst.GroupKey} to {best.GroupKey}.",
                    SourceRule = "channel_region_margin_reallocation",
                    SourceModel = "rules-v1",
                    Hypothesis = hypothesis,
                    ExplainabilityJson = JsonSerializer.Serialize(new
                    {
                        fromGroup = worst.GroupKey,
                        toGroup = best.GroupKey,
                        fromMarginPerOrder = Math.Round(worst.MarginPerOrder, 2),
                        toMarginPerOrder = Math.Round(best.MarginPerOrder, 2),
                        fromConversion = Math.Round(worst.ConversionRate, 4),
                        toConversion = Math.Round(best.ConversionRate, 4)
                    }),
                    ConfidenceScore = confidence,
                    EstimatedRevenueImpact = estimatedRevenue,
                    EstimatedMarginImpact = estimatedMargin,
                    EstimatedCashImpact = estimatedCash,
                    RecommendationActionTitle = "Reallocate sales focus",
                    RecommendationActionDescription = $"Reallocate {shiftOrders} planned sales slots from {worst.GroupKey} to {best.GroupKey}.",
                    WhyRecommended = "The destination channel/region shows better margin and conversion proxy.",
                    RecommendationPayloadJson = JsonSerializer.Serialize(new
                    {
                        from = worst.GroupKey,
                        to = best.GroupKey,
                        shiftedOrders = shiftOrders,
                        marginGap = Math.Round(marginGap, 2),
                        confidence = Math.Round(confidence, 2)
                    }),
                    Signals =
                    [
                        new OpportunityCandidateSignal("from_group_margin_per_order", worst.GroupKey, worst.MarginPerOrder, "currency_per_order", "Order", worst.GroupKey),
                        new OpportunityCandidateSignal("to_group_margin_per_order", best.GroupKey, best.MarginPerOrder, "currency_per_order", "Order", best.GroupKey),
                        new OpportunityCandidateSignal("shifted_orders", fingerprint, shiftOrders, "orders", "Order", fingerprint)
                    ]
                }
            ];
        }

        private List<OpportunityCandidate> Prioritize(IEnumerable<OpportunityCandidate> rawCandidates)
        {
            var candidates = rawCandidates
                .GroupBy(candidate => candidate.Fingerprint)
                .Select(group => group.OrderByDescending(item => item.ConfidenceScore).First())
                .ToList();

            if (candidates.Count == 0)
                return [];

            var maxImpact = candidates
                .Select(candidate => Math.Abs(candidate.EstimatedMarginImpact) + Math.Abs(candidate.EstimatedRevenueImpact * 0.2) + Math.Abs(candidate.EstimatedCashImpact * 0.1))
                .DefaultIfEmpty(1)
                .Max();

            foreach (var candidate in candidates)
            {
                var impact = Math.Abs(candidate.EstimatedMarginImpact)
                             + Math.Abs(candidate.EstimatedRevenueImpact * 0.2)
                             + Math.Abs(candidate.EstimatedCashImpact * 0.1);

                var impactScore = maxImpact <= 0 ? 0 : (impact / maxImpact) * 100;
                var priority = (candidate.ConfidenceScore * 0.6) + (impactScore * 0.4);
                candidate.PriorityScore = Clamp(priority, 0, 100);
                candidate.PriorityLabel = ResolvePriorityLabel(candidate.PriorityScore);
            }

            return candidates
                .OrderByDescending(candidate => candidate.PriorityScore)
                .ThenByDescending(candidate => candidate.ConfidenceScore)
                .ThenByDescending(candidate => candidate.EstimatedMarginImpact)
                .ToList();
        }

        private async Task<PersistResult> UpsertOpportunitiesAsync(
            Guid enterpriseId,
            Guid runId,
            IReadOnlyList<OpportunityCandidate> candidates,
            bool onlyOpenOpportunities,
            DateTime now)
        {
            var existing = await SafeGetAllAsync(_opportunityRepository,
                x => x.IsActive == true && x.EnterpriseId == enterpriseId);

            var existingByFingerprint = existing
                .Where(x => !string.IsNullOrWhiteSpace(x.Fingerprint))
                .ToDictionary(x => x.Fingerprint, x => x, StringComparer.OrdinalIgnoreCase);

            var createdByType = new Dictionary<string, double>(StringComparer.OrdinalIgnoreCase);
            var generated = 0;
            var updated = 0;

            foreach (var candidate in candidates)
            {
                if (existingByFingerprint.TryGetValue(candidate.Fingerprint, out var existingOpportunity))
                {
                    existingOpportunity.Type = candidate.Type;
                    existingOpportunity.Title = candidate.Title;
                    existingOpportunity.Description = candidate.Description;
                    existingOpportunity.SourceRule = candidate.SourceRule;
                    existingOpportunity.SourceModel = candidate.SourceModel;
                    existingOpportunity.Hypothesis = candidate.Hypothesis;
                    existingOpportunity.ExplainabilityJson = candidate.ExplainabilityJson;
                    existingOpportunity.RunId = runId;
                    existingOpportunity.ConfidenceScore = candidate.ConfidenceScore;
                    existingOpportunity.EstimatedRevenueImpact = candidate.EstimatedRevenueImpact;
                    existingOpportunity.EstimatedMarginImpact = candidate.EstimatedMarginImpact;
                    existingOpportunity.EstimatedCashImpact = candidate.EstimatedCashImpact;
                    existingOpportunity.PriorityScore = candidate.PriorityScore;
                    existingOpportunity.LastEvaluatedAt = now;
                    existingOpportunity.UpdatedAt = now;

                    if (existingOpportunity.Status == StatusArchived)
                        existingOpportunity.Status = StatusNew;

                    _opportunityRepository.Update(existingOpportunity);

                    await ReplaceSignalsAndRecommendationAsync(existingOpportunity.Id, candidate, now);
                    updated++;
                }
                else
                {
                    var opportunity = new Opportunity
                    {
                        Id = Guid.NewGuid(),
                        EnterpriseId = enterpriseId,
                        Type = candidate.Type,
                        Status = StatusNew,
                        Title = candidate.Title,
                        Description = candidate.Description,
                        SourceRule = candidate.SourceRule,
                        SourceModel = candidate.SourceModel,
                        Hypothesis = candidate.Hypothesis,
                        ExplainabilityJson = candidate.ExplainabilityJson,
                        Fingerprint = candidate.Fingerprint,
                        RunId = runId,
                        ConfidenceScore = candidate.ConfidenceScore,
                        EstimatedRevenueImpact = candidate.EstimatedRevenueImpact,
                        EstimatedMarginImpact = candidate.EstimatedMarginImpact,
                        EstimatedCashImpact = candidate.EstimatedCashImpact,
                        PriorityScore = candidate.PriorityScore,
                        DetectedAt = now,
                        LastEvaluatedAt = now,
                        CreatedAt = now,
                        UpdatedAt = now,
                        IsActive = true
                    };

                    await _opportunityRepository.CreateAsync(opportunity);

                    await CreateSignalsAsync(opportunity.Id, candidate.Signals, now);
                    await CreateRecommendationAsync(opportunity.Id, candidate, now);

                    generated++;
                    if (!createdByType.TryAdd(candidate.Type, 1))
                        createdByType[candidate.Type]++;

                    Log.Information(
                        "Opportunity recommendation generated. type={Type} title={Title} confidence={Score} marginImpact={MarginImpact} runId={RunId}",
                        candidate.Type,
                        candidate.Title,
                        Math.Round(candidate.ConfidenceScore, 2),
                        Math.Round(candidate.EstimatedMarginImpact, 2),
                        runId);
                }
            }

            var currentFingerprints = candidates
                .Select(candidate => candidate.Fingerprint)
                .ToHashSet(StringComparer.OrdinalIgnoreCase);

            var archived = 0;
            foreach (var opportunity in existing)
            {
                if (currentFingerprints.Contains(opportunity.Fingerprint))
                    continue;

                if (onlyOpenOpportunities && (opportunity.Status == StatusAccepted || opportunity.Status == StatusExecuted))
                    continue;

                if (opportunity.Status == StatusArchived)
                    continue;

                opportunity.Status = StatusArchived;
                opportunity.LastEvaluatedAt = now;
                opportunity.UpdatedAt = now;
                _opportunityRepository.Update(opportunity);
                archived++;
            }

            await _opportunityRepository.CommitAsync();

            return new PersistResult
            {
                Generated = generated,
                Updated = updated,
                Archived = archived,
                GeneratedByType = createdByType
            };
        }

        private async Task ReplaceSignalsAndRecommendationAsync(Guid opportunityId, OpportunityCandidate candidate, DateTime now)
        {
            var existingSignals = await SafeGetAllAsync(_signalRepository,
                x => x.IsActive == true && x.OpportunityId == opportunityId);

            foreach (var signal in existingSignals)
            {
                signal.IsActive = false;
                signal.UpdatedAt = now;
            }

            if (existingSignals.Count > 0)
                _signalRepository.UpdateRange(existingSignals);

            var existingRecommendation = await SafeGetAllAsync(_recommendationRepository,
                x => x.IsActive == true && x.OpportunityId == opportunityId);

            foreach (var recommendation in existingRecommendation)
            {
                recommendation.IsActive = false;
                recommendation.UpdatedAt = now;
            }

            if (existingRecommendation.Count > 0)
                _recommendationRepository.UpdateRange(existingRecommendation);

            await CreateSignalsAsync(opportunityId, candidate.Signals, now);
            await CreateRecommendationAsync(opportunityId, candidate, now);
        }

        private async Task CreateSignalsAsync(Guid opportunityId, IReadOnlyList<OpportunityCandidateSignal> signals, DateTime now)
        {
            if (signals.Count == 0)
                return;

            var entities = signals.Select(signal => new OpportunitySignal
            {
                Id = Guid.NewGuid(),
                OpportunityId = opportunityId,
                SignalType = signal.SignalType,
                SignalKey = signal.SignalKey,
                SignalValue = signal.SignalValue,
                Unit = signal.Unit,
                SourceEntity = signal.SourceEntity,
                SourceEntityId = signal.SourceEntityId,
                MetadataJson = signal.MetadataJson,
                CapturedAt = now,
                CreatedAt = now,
                UpdatedAt = now,
                IsActive = true
            }).ToList();

            await _signalRepository.CreateRangeAsync(entities);
        }

        private Task CreateRecommendationAsync(Guid opportunityId, OpportunityCandidate candidate, DateTime now)
        {
            var recommendation = new OpportunityRecommendation
            {
                Id = Guid.NewGuid(),
                OpportunityId = opportunityId,
                ActionTitle = candidate.RecommendationActionTitle,
                ActionDescription = candidate.RecommendationActionDescription,
                WhyRecommended = candidate.WhyRecommended,
                ActionPayloadJson = candidate.RecommendationPayloadJson,
                PriorityLabel = candidate.PriorityLabel,
                CreatedAt = now,
                UpdatedAt = now,
                IsActive = true
            };

            return _recommendationRepository.CreateAsync(recommendation);
        }

        private static HashSet<Guid> ResolveDemandOrderScope(IEnumerable<Order> orders)
        {
            var finalizedOrderIds = orders
                .Where(order => FinalizedOrderStatuses.Contains(order.Status))
                .Select(order => order.Id)
                .ToHashSet();

            if (finalizedOrderIds.Count > 0)
                return finalizedOrderIds;

            return orders
                .Where(order => order.Status != (int)EnumOrderStatus.Refund)
                .Select(order => order.Id)
                .ToHashSet();
        }

        private Dictionary<Guid, HashSet<Guid>> BuildOrderProductSets(RadarDataContext context)
        {
            var demandOrderIds = ResolveDemandOrderScope(context.Orders);

            return context.OrderedProducts
                .Where(line => line.OrderId.HasValue && demandOrderIds.Contains(line.OrderId.Value))
                .GroupBy(line => line.OrderId!.Value)
                .ToDictionary(
                    group => group.Key,
                    group => group.Select(line => line.ProductId).ToHashSet());
        }

        private Dictionary<Guid, string> BuildCustomerSegments(RadarDataContext context)
        {
            var demandOrderIds = ResolveDemandOrderScope(context.Orders);

            var customerStats = context.Orders
                .Where(order => order.CustomerId.HasValue && demandOrderIds.Contains(order.Id))
                .GroupBy(order => order.CustomerId!.Value)
                .Select(group => new
                {
                    CustomerId = group.Key,
                    AverageTicket = group.Average(order => Math.Max(0, order.TotalValue))
                })
                .OrderBy(stat => stat.AverageTicket)
                .ToList();

            if (customerStats.Count == 0)
                return [];

            var lowerIndex = (int)Math.Floor((customerStats.Count - 1) * 0.33);
            var upperIndex = (int)Math.Floor((customerStats.Count - 1) * 0.66);
            var lowerThreshold = customerStats[lowerIndex].AverageTicket;
            var upperThreshold = customerStats[upperIndex].AverageTicket;

            return customerStats.ToDictionary(
                stat => stat.CustomerId,
                stat => stat.AverageTicket <= lowerThreshold
                    ? "value"
                    : stat.AverageTicket >= upperThreshold
                        ? "premium"
                        : "standard");
        }

        private static List<PairMetric> BuildPairMetrics(Dictionary<Guid, HashSet<Guid>> orderProducts, IEnumerable<Guid> orderIds)
        {
            var supportCounts = new Dictionary<(Guid, Guid), int>();
            var baseCounts = new Dictionary<Guid, int>();
            var scopedOrderIds = orderIds.ToHashSet();
            var totalOrders = 0;

            foreach (var orderEntry in orderProducts.Where(item => scopedOrderIds.Contains(item.Key)))
            {
                var products = orderEntry.Value.ToList();
                if (products.Count < 2)
                    continue;

                totalOrders++;

                foreach (var product in products)
                {
                    if (!baseCounts.TryAdd(product, 1))
                        baseCounts[product]++;
                }

                for (var i = 0; i < products.Count; i++)
                {
                    for (var j = i + 1; j < products.Count; j++)
                    {
                        var left = products[i];
                        var right = products[j];
                        var key = left.CompareTo(right) < 0 ? (left, right) : (right, left);
                        if (!supportCounts.TryAdd(key, 1))
                            supportCounts[key]++;
                    }
                }
            }

            if (totalOrders <= 0)
                return [];

            var result = new List<PairMetric>();
            foreach (var support in supportCounts)
            {
                var productA = support.Key.Item1;
                var productB = support.Key.Item2;
                var supportCount = support.Value;
                var supportRatio = (double)supportCount / totalOrders;
                var confA = baseCounts.TryGetValue(productA, out var baseA) && baseA > 0 ? (double)supportCount / baseA : 0;
                var confB = baseCounts.TryGetValue(productB, out var baseB) && baseB > 0 ? (double)supportCount / baseB : 0;

                result.Add(new PairMetric
                {
                    ProductA = productA,
                    ProductB = productB,
                    Support = supportRatio,
                    SupportCount = supportCount,
                    Confidence = Math.Max(confA, confB)
                });
            }

            return result;
        }

        private static Dictionary<HashSet<Guid>, int> BuildTrioCounts(Dictionary<Guid, HashSet<Guid>> orderProducts, IEnumerable<Guid> orderIds)
        {
            var scoped = orderIds.ToHashSet();
            var comparer = HashSet<Guid>.CreateSetComparer();
            var counts = new Dictionary<HashSet<Guid>, int>(comparer);

            foreach (var entry in orderProducts.Where(item => scoped.Contains(item.Key)))
            {
                var products = entry.Value.ToList();
                if (products.Count < 3)
                    continue;

                for (var i = 0; i < products.Count; i++)
                {
                    for (var j = i + 1; j < products.Count; j++)
                    {
                        for (var k = j + 1; k < products.Count; k++)
                        {
                            var trio = new HashSet<Guid> { products[i], products[j], products[k] };
                            if (!counts.TryAdd(trio, 1))
                                counts[trio]++;
                        }
                    }
                }
            }

            return counts;
        }

        private static Dictionary<Guid, double> BuildDailyConsumptionByProduct(RadarDataContext context)
        {
            if (context.OrderedProducts.Count == 0)
                return [];

            var orderById = context.Orders.ToDictionary(order => order.Id, order => order);
            var demandOrderIds = ResolveDemandOrderScope(context.Orders);

            var lines = context.OrderedProducts
                .Where(line => line.OrderId.HasValue
                               && orderById.ContainsKey(line.OrderId.Value)
                               && demandOrderIds.Contains(line.OrderId.Value))
                .ToList();

            return lines
                .GroupBy(line => line.ProductId)
                .ToDictionary(
                    group => group.Key,
                    group => group.Sum(line => line.Quantity) / Math.Max(1, context.HistoryWindowDays));
        }

        private static Dictionary<Guid, double> BuildAverageCostByProduct(RadarDataContext context)
        {
            if (context.PayableItems.Count == 0)
                return [];

            var validReceivedBillIds = context.PayableBills
                .Where(bill => bill.ProductsReceivedAt.HasValue)
                .Select(bill => bill.Id)
                .ToHashSet();

            var lines = context.PayableItems
                .Where(item => validReceivedBillIds.Count == 0 || validReceivedBillIds.Contains(item.PayableBillId))
                .ToList();

            if (lines.Count == 0)
                lines = context.PayableItems;

            return lines
                .GroupBy(item => item.ProductId)
                .ToDictionary(
                    group => group.Key,
                    group =>
                    {
                        var totalQuantity = group.Sum(item => item.Quantity);
                        if (totalQuantity <= 0)
                            return 0d;

                        var totalAmount = group.Sum(item => item.Quantity * item.UnitValue);
                        return totalAmount / totalQuantity;
                    });
        }

        private static double ResolveCoverageDays(Product product, IReadOnlyDictionary<Guid, double> dailyConsumption)
        {
            if (!dailyConsumption.TryGetValue(product.Id, out var consumption) || consumption <= 0)
                return double.PositiveInfinity;

            return Math.Max(0, product.StorageQuantity) / consumption;
        }

        private static double ComputeReworkRate(IReadOnlyList<PayableBill> bills, IReadOnlyList<PayableBillProduct> lines)
        {
            if (bills.Count < 2 || lines.Count == 0)
                return 0;

            var billsByDate = bills
                .OrderBy(bill => bill.CreatedAt)
                .ToList();

            var repeatedWithinWindow = 0;
            var totalChecks = 0;

            for (var i = 1; i < billsByDate.Count; i++)
            {
                var current = billsByDate[i];
                var previous = billsByDate[i - 1];
                var days = (current.CreatedAt - previous.CreatedAt).TotalDays;
                if (days < 0 || days > 10)
                    continue;

                var previousProducts = lines
                    .Where(line => line.PayableBillId == previous.Id)
                    .Select(line => line.ProductId)
                    .ToHashSet();

                var currentProducts = lines
                    .Where(line => line.PayableBillId == current.Id)
                    .Select(line => line.ProductId)
                    .ToHashSet();

                if (previousProducts.Count == 0 || currentProducts.Count == 0)
                    continue;

                totalChecks++;
                if (previousProducts.Overlaps(currentProducts))
                    repeatedWithinWindow++;
            }

            if (totalChecks == 0)
                return 0;

            return (double)repeatedWithinWindow / totalChecks;
        }

        private static string InferSupplierKey(string description)
        {
            if (string.IsNullOrWhiteSpace(description))
                return "unknown_supplier";

            var raw = description.Trim();
            var delimiters = new[] { " - ", ":", "|", "/", "\\" };

            foreach (var delimiter in delimiters)
            {
                var split = raw.Split(delimiter, StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
                if (split.Length > 1 && split[0].Length >= 3)
                    return split[0].ToLowerInvariant();
            }

            var firstToken = raw.Split(' ', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .FirstOrDefault();

            return string.IsNullOrWhiteSpace(firstToken)
                ? "unknown_supplier"
                : firstToken.ToLowerInvariant();
        }

        private static string InferSalesChannel(Customer customer)
        {
            if (!string.IsNullOrWhiteSpace(customer.Document))
            {
                var digits = new string(customer.Document.Where(char.IsDigit).ToArray());
                if (digits.Length > 11)
                    return "b2b";
            }

            if (!string.IsNullOrWhiteSpace(customer.Email) && customer.Email.Contains("market", StringComparison.OrdinalIgnoreCase))
                return "marketplace";

            return "b2c";
        }

        private static string InferRegion(string? address)
        {
            if (string.IsNullOrWhiteSpace(address))
                return "unknown";

            var tokens = address
                .Split([',', ';', '|', '-'], StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .Reverse()
                .ToList();

            foreach (var token in tokens)
            {
                var normalized = token.Trim().ToUpperInvariant();
                if (normalized.Length == 2 && normalized.All(char.IsLetter))
                    return normalized;
            }

            var first = tokens.FirstOrDefault();
            if (string.IsNullOrWhiteSpace(first))
                return "unknown";

            return first.Trim().ToUpperInvariant();
        }

        private static string NormalizeStatus(string status)
        {
            return string.IsNullOrWhiteSpace(status)
                ? FeedbackIgnored
                : status.Trim().ToLowerInvariant();
        }

        private async Task UpdateKpiGaugesAsync(Guid enterpriseId)
        {
            var summary = await GetSummaryAsync(enterpriseId);
            AcceptanceRateGauge.WithLabels(enterpriseId.ToString()).Set(summary.AcceptanceRate);
            ImplementationRateGauge.WithLabels(enterpriseId.ToString()).Set(summary.ImplementationRate);
            UpliftRealVsEstimatedGauge.WithLabels(enterpriseId.ToString()).Set(summary.RealVsEstimatedUplift);
        }

        private OpportunityRunLogDTO MapRunLog(OpportunityRunLog runLog)
        {
            return new OpportunityRunLogDTO
            {
                Id = runLog.Id,
                RunId = runLog.RunId,
                EnterpriseId = runLog.EnterpriseId,
                RequestedByUserId = runLog.RequestedByUserId,
                TriggerType = runLog.TriggerType,
                Status = runLog.Status,
                StartedAt = runLog.StartedAt,
                FinishedAt = runLog.FinishedAt,
                TotalGenerated = runLog.TotalGenerated,
                TotalUpdated = runLog.TotalUpdated,
                TotalArchived = runLog.TotalArchived,
                DurationMs = runLog.DurationMs,
                DetectorStatsJson = runLog.DetectorStatsJson,
                ErrorMessage = runLog.ErrorMessage,
                CorrelationId = runLog.CorrelationId
            };
        }

        private void EnsureRadarEnabled()
        {
            if (!_settings.Enabled)
                throw new InsertDatabaseException("Opportunity radar is disabled by feature flag.");
        }

        private static double Clamp(double value, double min, double max)
        {
            return Math.Min(max, Math.Max(min, value));
        }

        private static string ResolvePriorityLabel(double priorityScore)
        {
            if (priorityScore >= 70)
                return "high";

            if (priorityScore >= 40)
                return "medium";

            return "low";
        }

        private static async Task<List<TEntity>> SafeGetAllAsync<TEntity>(
            IRepository<TEntity> repository,
            Expression<Func<TEntity, bool>>? predicate = null)
            where TEntity : BaseEntity
        {
            try
            {
                return (await repository.GetAllAsyncByFilter(false, null, null, predicate)).ToList();
            }
            catch (NotFoundDatabaseException)
            {
                return [];
            }
        }

        private sealed class RadarDataContext
        {
            public required List<Order> Orders { get; init; }
            public required List<OrderedProduct> OrderedProducts { get; init; }
            public required Dictionary<Guid, Product> ProductsById { get; init; }
            public required Dictionary<Guid, Customer> CustomersById { get; init; }
            public required List<PayableBill> PayableBills { get; init; }
            public required List<PayableBillProduct> PayableItems { get; init; }
            public required DateTime WindowStart { get; init; }
            public required int HistoryWindowDays { get; init; }
        }

        private sealed class PairMetric
        {
            public Guid ProductA { get; set; }
            public Guid ProductB { get; set; }
            public double Support { get; set; }
            public int SupportCount { get; set; }
            public double Confidence { get; set; }
        }

        private sealed class SupplierCostSnapshot
        {
            public string SupplierKey { get; set; } = string.Empty;
            public int BillCount { get; set; }
            public double Quantity { get; set; }
            public double BaseUnitCost { get; set; }
            public double AverageDelayDays { get; set; }
            public double ReworkRate { get; set; }
            public double ExtraFreightPerUnit { get; set; }
            public double TcoPerUnit { get; set; }
        }

        private sealed class CommercialGroupSnapshot
        {
            public string GroupKey { get; set; } = string.Empty;
            public int Orders { get; set; }
            public int FinalizedOrders { get; set; }
            public double Revenue { get; set; }
            public double Margin { get; set; }
            public double ConversionRate { get; set; }
            public double MarginPerOrder { get; set; }
            public double RevenuePerOrder { get; set; }
        }

        private sealed class OpportunityCandidate
        {
            public string Fingerprint { get; set; } = string.Empty;
            public string Type { get; set; } = string.Empty;
            public string Title { get; set; } = string.Empty;
            public string Description { get; set; } = string.Empty;
            public string SourceRule { get; set; } = string.Empty;
            public string SourceModel { get; set; } = string.Empty;
            public string Hypothesis { get; set; } = string.Empty;
            public string ExplainabilityJson { get; set; } = "{}";
            public double ConfidenceScore { get; set; }
            public double EstimatedRevenueImpact { get; set; }
            public double EstimatedMarginImpact { get; set; }
            public double EstimatedCashImpact { get; set; }
            public double PriorityScore { get; set; }
            public string PriorityLabel { get; set; } = "medium";
            public string RecommendationActionTitle { get; set; } = string.Empty;
            public string RecommendationActionDescription { get; set; } = string.Empty;
            public string WhyRecommended { get; set; } = string.Empty;
            public string RecommendationPayloadJson { get; set; } = "{}";
            public IReadOnlyList<OpportunityCandidateSignal> Signals { get; set; } = [];
        }

        private sealed class OpportunityCandidateSignal
        {
            public OpportunityCandidateSignal(
                string signalType,
                string signalKey,
                double signalValue,
                string unit,
                string sourceEntity,
                string sourceEntityId,
                string metadataJson = "{}")
            {
                SignalType = signalType;
                SignalKey = signalKey;
                SignalValue = signalValue;
                Unit = unit;
                SourceEntity = sourceEntity;
                SourceEntityId = sourceEntityId;
                MetadataJson = metadataJson;
            }

            public string SignalType { get; }
            public string SignalKey { get; }
            public double SignalValue { get; }
            public string Unit { get; }
            public string SourceEntity { get; }
            public string SourceEntityId { get; }
            public string MetadataJson { get; }
        }

        private sealed class PersistResult
        {
            public int Generated { get; set; }
            public int Updated { get; set; }
            public int Archived { get; set; }
            public Dictionary<string, double> GeneratedByType { get; set; } = [];
        }
    }
}

