version: '3.8'

services:
  evangelionerpv2:
    image: aureofjunior/evangelionerpv2:latest
    container_name: evangelionerpv2_web
    ports:
      - "5000:80"  # HOST 5000 - CONTAINER 80
    networks:
      - custom_network

  nginx:
    image: nginx:latest
    container_name: evangelionerpv2_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - evangelionerpv2
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge