name: Run Tests

on:
  pull_request:
    branches:
      - develop
      - release

permissions:
  contents: read

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Restore solution
      run: |
        dotnet restore EvangelionERPV2.sln

    - name: Build solution (Release)
      run: |
        dotnet build EvangelionERPV2.sln -c Release --no-restore

    - name: Test solution (Release)
      run: |
        dotnet test EvangelionERPV2.sln -c Release --no-build
