name: Terraform Setup

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches:
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Terraform code
      uses: actions/checkout@v2

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      run: terraform apply -var="aws_region=us-east-1" -auto-approve